export const cairoAreas = [
  { en: 'All Cairo', ar: 'كل القاهرة' },
  // East Greater Cairo
  { en: 'New Cairo', ar: 'القاهرة الجديدة' },
  { en: '5th Settlement', ar: 'التجمع الخامس' },
  { en: 'Madinaty', ar: 'مدينتي' },
  { en: 'Rehab City', ar: 'مدينة الرحاب' },
  { en: 'Shorouk City', ar: 'مدينة الشروق' },
  { en: 'Mostakbal City', ar: 'مدينة المستقبل' },
  { en: 'New Administrative Capital', ar: 'العاصمة الإدارية الجديدة' },
  { en: 'Obour City', ar: 'مدينة العبور' },
  { en: 'Badr City', ar: 'مدينة بدر' },
  // Central East
  { en: 'Nasr City', ar: 'مدينة نصر' },
  { en: 'Makram Ebeid', ar: 'مكرم عبيد' },
  { en: 'Abbas El Akkad', ar: 'عباس العقاد' },
  { en: 'Mostafa El Nahhas', ar: 'مصطفى النحاس' },
  { en: 'District 7 Nasr City', ar: 'الحي السابع مدينة نصر' },
  { en: 'District 8 Nasr City', ar: 'الحي الثامن مدينة نصر' },
  { en: 'District 10 Nasr City', ar: 'الحي العاشر مدينة نصر' },
  { en: 'Heliopolis', ar: 'مصر الجديدة' },
  { en: 'Nozha', ar: 'النزهة' },
  { en: 'New Nozha', ar: 'النزهة الجديدة' },
  { en: 'Sheraton', ar: 'شيراتون' },
  { en: 'Almazah', ar: 'الماظة' },
  { en: 'Hadayeq El Zeitoun', ar: 'حدائق الزيتون' },
  { en: 'Helmeyat El Zaytoun', ar: 'حلميات الزيتون' },
  { en: 'New Heliopolis', ar: 'هليوبوليس الجديدة' },
  { en: 'Ain Shams', ar: 'عين شمس' },
  { en: 'Matareya', ar: 'المطرية' },
  { en: 'Gesr Al Suez', ar: 'جسر السويس' },
  { en: 'Salam City', ar: 'مدينة السلام' },
  { en: 'Hadayek el-Kobba', ar: 'حدائق القبة' },
  { en: 'Marg', ar: 'المرج' },
  // Islamic Cairo / Historic
  { en: 'Khan El Khalili', ar: 'خان خليل' },
  { en: 'Bab El Sharia', ar: 'باب الشرعية' },
  { en: 'Bab El Futouh', ar: 'باب الفطور' },
  { en: 'Dirasa', ar: 'دراسة' },
  { en: 'Barakat Dirasa', ar: 'بركات دراسة' },
  { en: 'Abu Yusuf Taba', ar: 'ابو يوسف تبة' },
  { en: 'Taba', ar: 'تبة' },
  { en: 'Daweya', ar: 'دوية' },
  { en: 'Hussein Area', ar: 'منطقة الحسين' },
  { en: 'Madinat El Buouth', ar: 'مدينة البعوث' },
  { en: 'Manhal', ar: 'منهل' },
  { en: 'Gamaliya', ar: 'الغمالية' },
  // Central Cairo
  { en: 'Downtown', ar: 'وسط البلد' },
  { en: 'Garden City', ar: 'جاردن سيتي' },
  { en: 'Zamalek', ar: 'الزمالك' },
  { en: 'Shubra', ar: 'شبرا' },
  { en: 'Rod al-Farag', ar: 'روض الفرج' },
  { en: 'Abasiya', ar: 'العباسية' },
  { en: 'Old Cairo', ar: 'مصر القديمة' },
  { en: 'Ramses', ar: 'رمسيس' },
  { en: 'Tahrir Square', ar: 'ميدان التحرير' },
  { en: 'Ataba', ar: 'العتبة' },
  { en: 'Sayeda Zeinab', ar: 'السيدة زينب' },
  { en: 'Sayeda Aisha', ar: 'السيدة عائشة' },
  { en: 'Abbassia', ar: 'عباسية' },
  { en: 'Abdi Pasha', ar: 'عبدي باشا' },
  { en: 'Al Manial', ar: 'المنيل' },
  { en: 'El Fostat', ar: 'الفسطاط' },
  // South Cairo
  { en: 'Maadi', ar: 'المعادي' },
  { en: 'Zahraa Al Maadi', ar: 'زهراء المعادي' },
  { en: 'Degla Maadi', ar: 'دجلة المعادي' },
  { en: 'Zahraa', ar: 'زهراء' },
  { en: 'Basateen', ar: 'البساتين' },
  { en: 'Helwan', ar: 'حلوان' },
  { en: 'Hadayek Helwan', ar: 'حدائق حلوان' },
  { en: 'Katameya', ar: 'الكاتمية' },
  { en: 'Mokattam', ar: 'المقطم' },
  { en: '15 May City', ar: 'مدينة 15 مايو' },
  // West / Giza
  { en: 'Giza', ar: 'الجيزة' },
  { en: 'Dokki', ar: 'الدقي' },
  { en: 'Mohandessin', ar: 'المهندسين' },
  { en: 'Agouza', ar: 'العجوزة' },
  { en: 'Haram', ar: 'الهرم' },
  { en: 'Faisal', ar: 'فيصل' },
  { en: 'Sheikh Zayed', ar: 'الشيخ زايد' },
  { en: '6th of October', ar: 'السادس من أكتوبر' },
  { en: 'Hadayek October', ar: 'حدائق أكتوبر' },
  { en: 'Other', ar: 'أخرى' },
];

export const cairoCompounds = [
  { en: 'Hyde Park', ar: 'هايد بارك' },
  { en: 'Mivida', ar: 'ميفيدا' },
  { en: 'Mountain View iCity', ar: 'ماونتن فيو آي سيتي' },
  { en: 'Palm Hills New Cairo', ar: 'بالم هيلز نيو كايرو' },
  { en: 'Sarai', ar: 'سراي' },
  { en: 'Eastown', ar: 'إيستاون' },
  { en: 'Fifth Square', ar: 'فيفث سكوير' },
  { en: 'Taj City', ar: 'تاج سيتي' },
  { en: 'Villette', ar: 'فيليت' },
  { en: 'Al Burouj', ar: 'البرج' },
  { en: 'El Lotus', ar: 'اللوتس' },
  { en: 'Beit Al Watan', ar: 'بيت الوطن' },
  { en: 'Lake View Residence', ar: 'ليك فيو' },
  { en: 'Stone Park', ar: 'ستون' },
  { en: 'Zed East', ar: 'زيد ايست' },
  { en: 'Al Maqsad', ar: 'المقصد' },
  { en: 'Patio Oro', ar: 'الباتيو اورو' },
  { en: 'Gardenia', ar: 'جاردينيا' },
  { en: 'Midtown', ar: 'ميدتاون' },
  { en: 'Acacia', ar: 'أكاسيا' },
  { en: 'Al Narges', ar: 'النرجس' },
  { en: 'Tag Sultan', ar: 'تاج سلطان' },
  { en: 'Galleria Moon Valley', ar: 'جاليريا مون فالي' },
  { en: 'Amorada', ar: 'أمورادا' },
  { en: 'The Address East', ar: 'ذا أدرس ايست' },
  { en: 'Orla Residence', ar: 'اورلا' },
  { en: 'Privado', ar: 'بريفادو' },
  { en: 'Bellagio', ar: 'بيلاجيو' },
  { en: 'Wesal', ar: 'وصال' },
  { en: 'Jade Park', ar: 'جايد بارك' },
  { en: 'Porto New Cairo', ar: 'بورتو نيو كايرو' },
  { en: 'Al Hadaba Al Wosta', ar: 'الحدبة الوسطى' },
  { en: 'Diplomats District', ar: 'الدبلوماسيين' },
];
